# fly.toml app configuration file generated for reactivities-pk on 2024-10-06T06:40:09+05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'reactivities-pk'
primary_region = 'syd'

[build]
  image = 'saimsajid94/reactivities:latest'

[env]
  ASPNETCORE_URLS = "http://+:8080"
  Cloudinary__ApiKey = "651977115115685"
  Cloudinary__CloudName = "dt5pjlk3p"
  Facebook__AppId="536364895167291"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
